import Head from 'next/head';
import Image from 'next/image';

import React from 'react';
import { Announcement } from '../components/Announcement';
import { Button } from '../components/Button';
import { Card } from '../components/Card';
import { CTA } from '../components/CTA';
import { Feature } from '../components/Feature';
import { Footer } from '../components/Footer';
import { FrameworkDiagram } from '../components/FrameworkDiagram';
import { Header } from '../components/Header';

const features = [
    {
        title: 'Database',
        description: 'Store and manipulate data and files using a meta-schema and specific write rules.',
        src: '/resources/database.svg',
        alt: 'Database',
        href: '/',
    },
    {
        title: 'Workflows',
        description: 'Execute complex or simple actions on resources. We generate semantic SDK and doc.',
        src: '/resources/workflows.svg',
        alt: 'Workflows',
        href: '/',
    },
    {
        title: 'Hosting',
        description: 'Host web apps and sites distributed at lighting speed around the globe.',
        src: '/resources/hosting.svg',
        alt: 'Hosting',
        href: '/',
    },
    {
        title: 'Monitoring',
        description: 'Understand how your apps are used and act quickly.',
        src: '/resources/monitoring.svg',
        alt: 'Monitoring',
        href: '/',
    },
];

export default () => {
    return (
        <>
            <Head>
                <title>OwlGrid</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <div className="relative overflow-hidden min-h-screen md:flex md:flex-col">
                <Announcement />
                <Header />
                <div className="flex flex-col items-start sm:items-center mt-auto mb-auto pb-12">
                    <div className="container mx-auto max-w-5xl px-6 py-12 sm:py-3">
                        <div className="flex flex-col gap-2">
                            <div className="flex gap-2 sm:justify-center">
                                <span className="text-lg sm:text-xl leading-8 font-bold flex justify-center text-transparent bg-clip-text bg-gradient-to-br from-blue to-purple">
                                    Unleash your app superpowers
                                </span>
                                <span>✨</span>
                            </div>

                            <h1 className="text-primary sm:text-center sm:max-w-md sm:mx-auto lg:max-w-none">
                                Create cloud applications in a minute.
                            </h1>

                            <p className="subtitle mt-6 mb-3 sm:text-center sm:max-w-md sm:mx-auto">
                                OwlGrid allows product and IT teams to quickly implement robust apps backends.
                            </p>
                        </div>

                        <div className="mt-8 flex gap-x-4 sm:justify-center">
                            <Button href="#features" primary>
                                Learn more
                            </Button>
                            <Button href="/" secondary>
                                Stay informed
                            </Button>
                        </div>
                    </div>
                </div>

                <div className="absolute bottom-0 -z-10 transform-gpu overflow-hidden">
                    <svg
                        className="w-screen"
                        width="100%"
                        height="100%"
                        viewBox="0 0 1920 479"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <g filter="url(#filter0_f_101_38)">
                            <path
                                d="M1594.61 343.617C953.335 595.574 461.953 450.677 313.305 343.617C269.593 324.006 164.311 233.697 -24.0278 203.241C-259.451 165.171 -286.073 581.208 -77.5 675C131.073 768.792 1463.96 822.953 1825 739.5C2320.5 728.5 2396.23 28.6725 1594.61 343.617Z"
                                fill="url(#paint0_linear_101_38)"
                            />
                        </g>
                        <defs>
                            <filter
                                id="filter0_f_101_38"
                                x="-418.615"
                                y="0.786743"
                                width="2816.58"
                                height="979.972"
                                filterUnits="userSpaceOnUse"
                                colorInterpolationFilters="sRGB"
                            >
                                <feFlood floodOpacity="0" result="BackgroundImageFix" />
                                <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
                                <feGaussianBlur stdDeviation="100" result="effect1_foregroundBlur_101_38" />
                            </filter>
                            <linearGradient
                                id="paint0_linear_101_38"
                                x1="1817.5"
                                y1="491"
                                x2="1536.13"
                                y2="-317.432"
                                gradientUnits="userSpaceOnUse"
                            >
                                <stop stopColor="#945FFE" />
                                <stop offset="1" stopColor="#0079FF" />
                            </linearGradient>
                        </defs>
                    </svg>
                </div>
            </div>

            <main className="overflow-x-hidden">
                <section className="wrapper py-24 space-y-24" id="value">
                    <Feature
                        heading={
                            <>
                                Implement app backends in <span className="text-blue">record</span> time.
                            </>
                        }
                        description={
                            <>
                                OwlGrid provides a catalog of integrated and ready-to-use resources to set up SaaS and
                                mobile application backends in record time.
                                <br />
                                <br />
                                Spend time on your core value: implement the functional logic.
                            </>
                        }
                        src="/placeholder.png"
                        alt="Placeholder"
                    />
                    <Feature
                        heading={
                            <>
                                Focus on the <span className="text-purple">features</span>, we handle the technique.
                            </>
                        }
                        description="60% of the tasks spent on an application backend have no added value. Stop reinventing the wheel every project and start using a perfectly integrated environment custom-built for developers."
                        src="/placeholder.png"
                        alt="Placeholder"
                        reversed
                    />
                    <Feature
                        heading={
                            <>
                                Build applications that <span className="text-blue">last</span>.
                            </>
                        }
                        description={
                            <>
                                Tired of unmaintainable AWS app backends and don’t want to create throw-away no-code
                                apps?
                                <br />
                                <br />
                                We provide you with a set of best practices by design: auto-generated documentation,
                                resource reuse with templates, data mock, etc.
                            </>
                        }
                        src="/placeholder.png"
                        alt="Placeholder"
                    />

                    {/* <div className='flex justify-center'>
            <Button href="/" primary>
              ⏱️ How OwlGrid can crush your delivery time
              <ArrowRightIcon className='h-6 w-6'/>
            </Button>
          </div> */}
                </section>

                <section
                    className="relative py-12 bg-gradient bg-gradient-to-br from-blue to-purple sm:bg-none"
                    id="features"
                >
                    <Image
                        src="/resources_bg.svg"
                        alt="Background image"
                        width={1920}
                        height={768}
                        className="hidden sm:block absolute -z-10 inset-0 h-full w-full bg-cover bg-center"
                    />

                    <div className="wrapper">
                        <div className="flex flex-col gap-4 items-center my-3">
                            <h2 className="text-white">Ready to use resources:</h2>
                            <p className="subtitle-white">Everything you need to create a modern SaaS or mobile app.</p>
                        </div>

                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 py-12">
                            {features.map((elem, i) => (
                                <Card
                                    key={i}
                                    title={elem.title}
                                    description={elem.description}
                                    src={elem.src}
                                    alt={elem.alt}
                                    href={elem.href}
                                />
                            ))}
                        </div>
                    </div>
                    <p className="subtitle-white text-center my-3 lg:my-6">+ more resources on the way 🤫</p>

                    {/* <div className='flex justify-center my-6'>
                      <Button href="/" tertiary>
                        ⚡️ <span className='text-transparent bg-clip-text bg-gradient-to-br from-blue to-purple'>Learn more about our features </span>

                        <svg width="20" height="21" viewBox="0 0 20 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path d="M11.8225 18.8867C12.1183 18.8867 12.4036 18.7705 12.6572 18.5275L19.6196 11.565C19.8627 11.3325 20 11.0156 20 10.6986C20 10.3711 19.8627 10.0541 19.6196 9.82171L12.6783 2.88035C12.4036 2.61622 12.1183 2.5 11.8225 2.5C11.1463 2.5 10.6603 2.97544 10.6603 3.61992C10.6603 3.958 10.7977 4.24326 11.009 4.45457L13.3862 6.86344L16.4501 9.66323L13.9989 9.51532H1.19387C0.486001 9.51532 0 10.0013 0 10.6986C0 11.3854 0.486001 11.8714 1.19387 11.8714H13.9989L16.4501 11.7235L13.3862 14.5232L11.009 16.9321C10.7977 17.1434 10.6603 17.4287 10.6603 17.7668C10.6603 18.4113 11.1463 18.8867 11.8225 18.8867Z" fill="url(#paint0_linear_247_38)"/>
                          <defs>
                          <linearGradient id="paint0_linear_247_38" x1="17.62" y1="17.3627" x2="4.70615" y2="0.862825" gradientUnits="userSpaceOnUse">
                            <stop stopColor="#945FFE"/>
                            <stop offset="1" stopColor="#0079FF"/>
                          </linearGradient>
                          </defs>
                        </svg>
                      </Button>
                    </div> */}
                </section>

                <section className="wrapper py-24">
                    <div className="flex flex-col items-center justify-center gap-4">
                        <h2 className="text-primary text-center">Open-source framework 🔨</h2>
                        <p className="subtitle text-center">Based on well-proven open-source technologies.</p>
                    </div>

                    <div className="my-12">
                        <FrameworkDiagram />
                    </div>
                    <Image
                        src="/framework.png"
                        alt="Open source framework"
                        width={1150}
                        height={516}
                        className="my-12"
                    />
                </section>

                <section className="relative md:h-screen" id="app-builders">
                    <Image
                        src="/person.png"
                        alt="Background image"
                        width={1920}
                        height={1038}
                        className="block aspect-video md:absolute -z-10 inset-0 sm:h-full w-full object-cover bg-center"
                    />
                    <div className="wrapper py-12 sm:py-24 flex md:items-center md:h-screen">
                        <div className="space-y-6 sm:space-y-12">
                            <h2 className="text-primary md:text-white">Hello App Builders 👋🏻</h2>
                            <div className="max-w-prose md:max-w-md space-y-4">
                                <p className="md:text-white">
                                    We believe that building applications is a complete skill. Today, applications are
                                    built by two separate jobs: the &quot;products&quot; and the &quot;techs&quot;. This
                                    leads to latency and inaccuracies. We need to change this way of working.
                                </p>
                                <p className="md:text-white">
                                    OwlGrid answers this problem. Having both strong product skills (user experience)
                                    and technical skills (how applications works), App Builders job is to quickly create
                                    powerful applications that respond very precisely to user needs.
                                </p>
                                <p className="md:text-white">
                                    We built OwlGrid to give App Builders the right tool to put their potential to work.
                                </p>
                            </div>
                        </div>
                    </div>
                </section>

                <CTA />
            </main>
            <Footer />
        </>
    );
};
